### ISSUE TITLE
usb.core.USBError: [Errno 22] Invalid parameter while using dev.ctrl_transfer in Windows

### ISSUE THREAD

**Issue by Devansh0210** [pyusb/pyusb#474] opened 2023-03-19 10:28 UTC
I'm trying to run simple `GET_REPORT` in HID Class example in Raspberry Pi Pico using TinyUSB:

When I try to run following script in Linux, it works perfectly and I get desired output:
```python
import usb.core
from usb.util import *
import sys


dev = usb.core.find(idVendor=0xcafe, idProduct=0x4004)


cfg = dev[0]

class ReportType:
    GET_REPORT      = 0x01
    GET_IDLE        = 0x02
    GET_PROTOCOL    = 0x03
    SET_REPORT      = 0x09
    SET_IDLE        = 0x0A
    SET_PROTOCOL    = 0x0B

st = dev.ctrl_transfer(
                ENDPOINT_IN | CTRL_TYPE_CLASS | CTRL_RECIPIENT_INTERFACE,
                ReportType.GET_REPORT,
                0x0200,
                0,
                64
                )

print("".join(map(chr, st)))
```
It prints correct output in `print` statement while running in linux but in windows I'm getting following error:
```
2023-03-19 15:45:57,451 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<WinDLL 'C:\Users\devan\Downloads\libusb-1.0.26-binaries\VS2015-x64\dll\libusb-1.0.dll', handle 7ffe7eb50000 at 0x1c3a133b3a0>)
2023-03-19 15:45:57,459 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2023-03-19 15:45:57,459 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
  File "C:\Users\devan\Downloads\src\pyusb\usb\core.py", line 1090, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
  File "C:\Users\devan\Downloads\src\pyusb\usb\_debug.py", line 62, in do_trace
    return f(*args, **named_args)
  File "C:\Users\devan\Downloads\src\pyusb\usb\backend\libusb1.py", line 900, in ctrl_transfer
    ret = _check(self.lib.libusb_control_transfer(
  File "C:\Users\devan\Downloads\src\pyusb\usb\backend\libusb1.py", line 606, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 22] Invalid parameter
```

I've also run script with `PYUSB_DEBUG=debug` and it shows following logs:
```
2023-03-19 15:55:35,153 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<WinDLL 'C:\Users\devan\Downloads\libusb-1.0.26-binaries\VS2015-x64\dll\libusb-1.0.dll', handle 7ffe8ae50000 at 0x187e0e0aef0>)
2023-03-19 15:55:35,169 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2023-03-19 15:55:35,169 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
2023-03-19 15:55:35,201 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x00000187E2D79240>)
2023-03-19 15:55:35,201 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x00000187E2D793C0>)
2023-03-19 15:55:35,201 DEBUG:usb.backend.libusb1:_Device._finalize_object()
2023-03-19 15:55:35,201 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x00000187E2D792A0>)
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_Device._finalize_object()
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x00000187E2D79420>)
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_Device._finalize_object()
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x00000187E2D79240>)
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_Device._finalize_object()
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x00000187E2D79240>, 0)
2023-03-19 15:55:35,209 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x00000187E2D79240>)
2023-03-19 15:55:35,273 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x00000187E0E09630>, 0)
2023-03-19 15:55:35,273 DEBUG:usb.backend.libusb1:_LibUSB.ctrl_transfer(<usb.backend.libusb1._DeviceHandle object at 0x00000187E0E09630>, 161, 1, 512, 0, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2023-03-19 15:55:35,273 DEBUG:usb.backend.libusb1: 
--------- Length of Packet : 64 -----------
Traceback (most recent call last):
  File "C:\Users\devan\Downloads\usb_test.py", line 19, in <module>
    st = dev.ctrl_transfer(
  File "C:\Users\devan\Downloads\src\pyusb\usb\core.py", line 1090, in ctrl_transfer
    ret = self._ctx.backend.ctrl_transfer(
  File "C:\Users\devan\Downloads\src\pyusb\usb\_debug.py", line 62, in do_trace
    return f(*args, **named_args)
  File "C:\Users\devan\Downloads\src\pyusb\usb\backend\libusb1.py", line 900, in ctrl_transfer
    ret = _check(self.lib.libusb_control_transfer(
  File "C:\Users\devan\Downloads\src\pyusb\usb\backend\libusb1.py", line 606, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 22] Invalid parameter
2023-03-19 15:55:35,287 DEBUG:usb.backend.libusb1:_LibUSB.release_interface(<usb.backend.libusb1._DeviceHandle object at 0x00000187E0E09630>, 0)
2023-03-19 15:55:35,287 DEBUG:usb.backend.libusb1:_LibUSB.close_device(<usb.backend.libusb1._DeviceHandle object at 0x00000187E0E09630>)       
2023-03-19 15:55:35,287 DEBUG:usb.backend.libusb1:_Device._finalize_object()
2023-03-19 15:55:35,287 DEBUG:usb.backend.libusb1:_LibUSB._finalize_object()
```

I'm not getting the reason of this error

**Comment by jonasmalacofilho** [comment] 2023-03-19 19:49
It points to some limitation of the backend: in this instance, libusb.

It might be relevant that the device is a HID: assuming you haven't messed with swapping the driver, libusb actually emulates raw USB I/O over the Microsoft Generic HID driver. While `GET_REPORT` would be expected to work, maybe libusb for some reason failed to detect/handle it?

In any case, you should check the libusb docs for that specific error, and also enable libusb debug info. If the issue is still unclear after doing those things, maybe try to reaching out to the libusb folks.

P.S. Closing this as it doesn't appear to be related to PyUSB (for now).

**Closed by jonasmalacofilho** 2023-03-19 19:49 UTC
