### ISSUE TITLE
The library need a stub-files to simplify usage

### ISSUE THREAD

**Issue by o-murphy** [pyusb/pyusb#513] opened 2024-05-12 23:48 UTC
I can write a .pyi stubs for a library

**Comment by mcuee** [comment] 2024-05-26 03:25
Maybe you want to elaborate what you want to achieve and give some examples. Thanks.

**Comment by o-murphy** [comment] 2024-05-27 06:54
> Maybe you want to elaborate what you want to achieve and give some examples. Thanks.

already started with it #514 
I just want to adjust library to [PEP484](https://peps.python.org/pep-0484/) [PEP561](https://peps.python.org/pep-0561) specs

**Comment by jonasmalacofilho** [comment] 2024-07-10 02:07
Duplicate of #470, keeping only the older issue.

**Closed by jonasmalacofilho** 2024-07-10 02:07 UTC
Labels: enhancement, duplicate
